const homeNav = document.getElementById('home-nav');
homeNav.style.backgroundColor = 'skyblue';
const navDivId = document.getElementById('nav-div-id');
const ideaDiv = document.getElementById('idea');
/* ideaDiv.style.display = 'flex';
ideaDiv.style.justifyItems = 'spaceBetween'; */
navDivId.style.display = 'flex';
navDivId.style.justifyItems = 'spaceBetween';
const buttonArea = document.getElementById('button-area');
buttonArea.style.display = 'flex';
buttonArea.style.justifyContent = 'spaceBetween';
const body = document.body;
body.style.backgroundColor = 'rgba(229, 93, 131, 1)';